name: Liquibase_Docker_GitHub-Hosted

on: [push]

env:
    LB_ENVIRONMENT: DEV
    LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-root.xml
    LIQUIBASE_COMMAND_TAG: ${{ github.run_number }}
# on:
#  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
# note the below assumes that a host path or volume is mounted into the container at ./Docker (or action will fail) !!!
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: liquibase-github-actions/validate@v4.25.1
      with:
        
          classpath: 'database/sql'
          changeLogFile: 'db.changelog-root.xml'
          username: ${{ secrets.LIQUIBASE_USERNAME }}
          password: ${{ secrets.LIQUIBASE_PASSWORD }}
          url: ${{ secrets.LIQUIBASE_URL }}
          
 
