name: Liquibase_Docker_GitHub-Hosted

on: [push]

env:
    LB_ENVIRONMENT: DEV
    LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-root.xml
    LIQUIBASE_COMMAND_TAG: ${{ github.run_number }}
# on:
#  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LIQUIBASE:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Run 'Status' to validate connection	    
      uses: liquibase-github-actions/status@v4.25.1
      with:   
          classpath: 'database/sql'
          changeLogFile: 'db.changelog-root.xml'
          username: ${{ secrets.LIQUIBASE_USERNAME }}
          password: ${{ secrets.LIQUIBASE_PASSWORD }}
          url: ${{ secrets.LIQUIBASE_URL }}
          logLevel: INFO

    - name: Run 'Update' against database	    
      uses: liquibase-github-actions/validate@v4.25.1
      with:   
          classpath: 'database/sql'
          changeLogFile: 'db.changelog-root.xml'
          url: ${{ secrets.LIQUIBASE_URL }}
          logLevel: INFO

    - name: Run 'History'	    
      uses: liquibase-github-actions/history@v4.25.1
      with:    
          classpath: 'database/sql'
          changeLogFile: 'db.changelog-root.xml'
          username: ${{ secrets.LIQUIBASE_USERNAME }}
          password: ${{ secrets.LIQUIBASE_PASSWORD }}
          url: ${{ secrets.LIQUIBASE_URL }}
          logLevel: INFO
 
